### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by julienmarie** [trbngr/elixir_cqrs_tools#25]
Hello,

I'm getting this error:
```== Compilation error in file lib/goethe/orders/commands/addcoupon.ex ==
** (ArgumentError) invalid option :required for field/3
    (ecto 3.8.3) lib/ecto/schema.ex:2201: Ecto.Schema.check_options!/3
    (ecto 3.8.3) lib/ecto/schema.ex:1908: Ecto.Schema.__field__/4
    (elixir 1.13.3) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17.1) erl_eval.erl:123: :erl_eval.exprs/5
    (stdlib 3.17.1) erl_eval.erl:919: :erl_eval.try_clauses/8
    (stdlib 3.17.1) erl_eval.erl:123: :erl_eval.exprs/5```

Here is my code:

```
defmodule Goethe.Orders.Command.AddCoupon do
  use Cqrs.Command, dispatcher: Goethe.EventApp

  field :id, :binary_id
  field :coupon, :string

  derive_event Goethe.Orders.Events.CouponAdded

end
```

and my deps:

```defp deps do
    [
      {:phoenix, "~> 1.6.6"},
      {:phoenix_ecto, "~> 4.4"},
      {:ecto_sql, "~> 3.6"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.17.5"},
      {:floki, ">= 0.30.0", only: :test},
      {:phoenix_live_dashboard, "~> 0.6"},
      {:esbuild, "~> 0.3", runtime: Mix.env() == :dev},
      {:swoosh, "~> 1.3"},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:gettext, "~> 0.18"},
      {:jason, "~> 1.2"},
      {:plug_cowboy, "~> 2.5"},
      {:commanded, "~> 1.3"},
      {:commanded_ecto_projections, "~> 1.2"},
      {:commanded_extreme_adapter, "~> 1.1"},
      {:cqrs_tools, "~> 0.5.28"},
    ]
  end```

Any idea what I'm doing wrong?

**Comment by julienmarie** [comment]
Fixed by downgrading ecto to :
```
      {:ecto, "~> 3.7.1"},
      {:ecto_sql, "~> 3.7.2"},
```

**Comment by trbngr** [comment]
Ooh. Nice find. I will make sure this works for Ecto 3.8+ in [Blunt](https://github.com/blunt-elixir/blunt).

BTW. Blunt is the "polished" version of this lib. The docs are not done but on the way.

**Comment by julienmarie** [comment]
Oh what's the difference between blunt and cqrs_tools ?

**Comment by trbngr** [comment]
There's not a whole lot of difference to the end-user.

`blunt`'s whole purpose was to take the lessons learned from writing `cqrs_tools` and apply them.

`cqrs_tools` generates a BUNCH of inline code instead of simply delegating to static modules. In a largish project this lead to triggering a very slow compilation of the whole project when editing a single file. It was so bad, I decided to rethink the whole project. 😲

I also didn't really like the name `cqrs_tools`. Personal preference but I felt it was too generic and forgettable.

There's also some testing code I quite like in `blunt`.

I'm working on documenting and writing samples for `blunt` right now. 

If you're up to it, I'd like to know if there's any real work - other than changing a namespace - in porting an app from `cqrs_tools` to `blunt`. I've ported a pretty large app successfully.  But my team and I took a very iterative approach.

**Comment by trbngr** [comment]
Actually, I take that back.

There is a *big* difference.

Blunt, by default, splits the command/query definitions from the handling of said commands/queries into two modules. This allowed me to ensure that the files touched would only be recompiled.

It also is very configurable in the "dispatch pipeline". The [CustomDispatchStrategy](https://github.com/blunt-elixir/blunt/blob/reorg/apps/blunt/test/support/custom_dispatch_strategy.ex) allows each project to define the dispatch pipeline that makes the most sense to that project in particular.

I will be writing about this, in detail, in the documentation and "marketing" site
